

services:
  app:
   depends_on:
    - db
   image: eclipse-temurin:17
   ports:
    - 8082:8082
   tty: true
   volumes:
    - ./server:/var/www/html/server
   working_dir: /var/www/html/server
  db:
   ports:
    - "5432:5432"
   image: postgres
   restart: always
   environment:
    POSTGRES_PASSWORD: root
    POSTGRES_USER: root
   volumes:
    - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  pgdata:
